### ISSUE TITLE
Changing Test Window in 4.1 Has No Effect

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#72]
Running Godot 3.2RC2 -- Windows 10 -- No errors only messages in the Output window

![image](https://user-images.githubusercontent.com/2214652/72859263-c9f95180-3c88-11ea-8785-ef810df67094.png)

![image](https://user-images.githubusercontent.com/2214652/72859230-adf5b000-3c88-11ea-8882-60e72cfc2291.png)

Nothing changes in the test window

![image](https://user-images.githubusercontent.com/2214652/72859296-e1d0d580-3c88-11ea-8568-f0d5d260d654.png)

**Comment by CodeDarigan** [comment]
path was hardcoded instead of read. Should be fixed by ac45088303facbcc59c403a618a23d10bab2de18

**Comment by paulhocker** [comment]
i'll try that one out for you now

**Comment by paulhocker** [comment]
Using the latest from master this is still occuring. I have tried changing and then exiting godot and going back in, but that does not work either.

One interesting thing is that it does not show the directory in the dropdown, but it does show the scripts in the directory i entered?

![image](https://user-images.githubusercontent.com/2214652/72952430-7275e700-3d57-11ea-84de-f05d41db55ea.png)

This problem is happening on 3.1 and 3.2RC2

**Comment by CodeDarigan** [comment]
198dcba1665990fe6838b45c6f79f093e8fbfc7a should have solved this.

**Comment by paulhocker** [comment]
I really think the new test system is great. Thank you for making it work with Autoload's now -- it will make life so much easier.

The new CLI is pretty slick -- and by the way specifying a specific directory with the -run_dir= option works flawlessly

keep it up!!

**Comment by CodeDarigan** [comment]
So everything is working fine? 

Thanks! I was trying to work on my project but some of these new features (debuggable tests were sorely needed)

**Comment by paulhocker** [comment]
everything appears to be working with the exception of the test directory setting. it refuses to change on the interface

is the merge above you mentioned in master bransh? that is where I pulled the source from.

**Comment by CodeDarigan** [comment]
It should be.

It doesn't change immediately, you need to min/max to refresh.

I could try using process to check if its changed. (ProjectSettings has no signal).

**Comment by CodeDarigan** [comment]
Okay added a check in process for an updated dir. It should change immediately now. 03be8f2e2909dcbd21ee1ebb5a20940926bfb73d

**Comment by paulhocker** [comment]
this is working perfectly now -- i think you can close this one -- nice job!
